
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\PRO\PycharmProjects\Assimit\app\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("515x448")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 448,
    width = 515,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    24.0,
    64.0,
    anchor="nw",
    text="Col 1",
    fill="#828282",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    374.0,
    64.0,
    anchor="nw",
    text="Col 2",
    fill="#828282",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_text(
    450.0,
    64.0,
    anchor="nw",
    text="Col 3",
    fill="#828282",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_rectangle(
    24.0,
    92.0,
    491.0,
    428.0,
    fill="#000000",
    outline="")

canvas.create_text(
    24.0,
    24.0,
    anchor="nw",
    text="Title",
    fill="#000000",
    font=("Inter SemiBold", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
